version: '2'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper
    networks:
      sample_04_vertx_net:
        ipv4_address: 172.28.1.1
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  database:
    image: postgres
    hostname: postgres
    networks:
      sample_04_vertx_net:
        ipv4_address: 172.28.1.2
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./sql/create-database.sql:/docker-entrypoint-initdb.d/00-create-database.sql
      - ./sql/insert-sample.sql:/docker-entrypoint-initdb.d/01-insert-sample.sql

  talan-http:
    build: ./http/
    networks:
      sample_04_vertx_net:
        ipv4_address: 172.28.1.3
    environment:
      ZOOKEEPER_HOST: zookeeper
      VERTX_CLUSTER_HOST: 172.28.1.3
      VERTX_CLUSTER_PORT: 36789
    depends_on:
      - zookeeper
      - talan-database
    ports:
      - "9000:9000"

  talan-database:
    build: ./database/
    networks:
      sample_04_vertx_net:
        ipv4_address: 172.28.1.4
    environment:
      ZOOKEEPER_HOST: zookeeper
      VERTX_CLUSTER_HOST: 172.28.1.4
      VERTX_CLUSTER_PORT: 36789
      JDBC_URL: jdbc:postgresql://database:5432/postgres
      JDBC_PASSWORD: postgres
      JDBC_USERNAME: postgres
      JDBC_DRIVER: org.postgresql.Driver
    depends_on:
      - zookeeper
      - database

networks:
  sample_04_vertx_net:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
